# Устанавливает префикс для сохранения версий пакетов в package.json
# Обновления пакетов ограничены патч изменениями (напр, ~1.2.3 до 1.2.x, но не до 1.3.x и не до 1.x.x)
# https://pnpm.io/settings#saveprefix
savePrefix: '~'

# https://pnpm.io/settings#symlink
# symlink: false

# https://pnpm.io/settings#node-linker
# nodeLinker: hoisted

# https://pnpm.io/settings#shamefullyhoist
# shamefullyHoist: true

#supportedArchitectures:
#  cpu:
#    - x64
#  os:
#    - win32
#    - linux

###

# https://pnpm.io/cli/run#enable-pre-post-scripts
enablePrePostScripts: true

# https://pnpm.io/settings#networkconcurrency
networkConcurrency: 48

# https://pnpm.io/settings#childconcurrency
childConcurrency: 24

# https://pnpm.io/settings#strictpeerdependencies
strictPeerDependencies: false

# https://pnpm.io/settings#dedupeinjecteddeps
dedupeInjectedDeps: true

# https://pnpm.io/settings#packagemanagerstrict
packageManagerStrict: false

# https://pnpm.io/settings#sideeffectscache
sideEffectsCache: false

# https://pnpm.io/settings#shellemulator
shellEmulator: true

# https://pnpm.io/settings#onlybuiltdependencies
onlyBuiltDependencies:
    - puppeteer